name: Pipeline
on:
  push:
  schedule:
  - cron: '0 1 * * 1' # Every Monday at 1AM UTC
jobs:
  tests:
    uses: Invoca/ruby-test-matrix-workflow/.github/workflows/ruby-test-matrix.yml@main
  coveralls:
    - name: Coveralls
      if: ${{ env.BUNDLE_GEMFILE == 'Gemfile' }}
      steps:
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
